#This script carries out the model performance evaluations and produces the corresponding manuscript figures and supplementary tables
library("boot")

rm(list=ls())
path <-"/Volumes/share/mnt/Data0/PROJECTS/CROPSeq/Manuscript/GitHub/Scripts/6.Predictive_models/Finalised/"
setwd(paste0(path, "/3.Predictions"))

source(paste0(path, "/2.Scripts/EvaluatePredictionModelFunctions.R"))

####################
#Load prediction  and variable importance data 
####################
#################### Prediction data
#astrocytes
all_rf_factors_powered <- read.csv("RF_Results/Astrocytes/Astrocyte_trainingData_pluspredictions.csv")
colnames(all_rf_factors_powered)[grep("ABCScore_ENCODE",colnames(all_rf_factors_powered))]="ABC_Score"  
#K562 
K562_EGPs<- read.csv("RF_Results/K562/K562_trainingData_pluspredictions.csv")
#Subset the astrocyte prediction data for EG pairs with ENCODE prediction data available
all_rf_factors_powered_encode <- all_rf_factors_powered[all_rf_factors_powered$ENCODE_overlap.Exists,]

####################Variable importance
importance_astro <- read.csv("RF_Results/Astrocytes/EG_Variable_Importance_EGrf_Power_subset_HitPermissive_NegZ_cv.csv")
importance_K562 <- read.csv("RF_Results/K562/EG_Variable_Importance_EGrf.Extended_K562_EGPs_Significant_NegEffectSize_cv.csv")


####################
#Code for Figure 7B and Extended Data Figure 9D
###################
setwd("../4.Figures_Tables/")

##Setting colors
plot_cols_astro <- plot_cols[str_detect(names(plot_cols), "Plus|Replace",negate = T)]

####Create Precision-Recall plots for the different models performed on Astrocytes
aucLists <- plotSubsetsAUCs(all_rf_factors_powered_encode,
                            plot_cols = plot_cols_astro,dataset.name = 'Astrocytes')

####Create Precision-Recall plots for the different models performed on K562
plot_cols_K562 <- plot_cols[str_detect(names(plot_cols), "Plus|Replace",negate = T)]
aucLists <- plotSubsetsAUCs(K562_EGPs, hit = "Significant_NegEffectSize",
                            plot_cols_K562,dataset.name = 'K562')


####Compare PR curves between models in Astrocytes and K562  displaying recommended threshold for rE2G and rE2G-extended models
Astrocytes_pr <- aucComparison(all_rf_factors_powered_encode, plot_cols = plot_cols_astro, 
                               probability = T, plot.type = "pr", add.recall.point = T)
K562_pr <- aucComparison(K562_EGPs, plot_cols = plot_cols_K562, Hit = "Significant_NegEffectSize",
                         probability = T, plot.type = "pr", add.recall.point = T)

le <- get_legend(K562_pr)
Astrocytes_pr <- Astrocytes_pr + theme(legend.position = "none") 
K562_pr <- K562_pr + theme(legend.position = "none")
plots <- plot_grid(Astrocytes_pr, K562_pr, label_size = 20)
pdf("7B.Performance_Astrocytes_K562_PR.pdf", height = h_margin * 3 / 10, width = w_margin *2 /3)
plot_grid(plots, le, rel_heights = c(1,0.2), ncol = 1)
dev.off()



###########################
##Code for Extended Data Figure 9B
##########################
aucvars <- c("rE2G.DNAseOnly","ABC_Score","Distance",
             colnames(all_rf_factors_powered_encode)[str_detect(colnames(all_rf_factors_powered_encode), ".removed|rf")])

#Generate barplots showing AUPRC in astrocytes models  with confidence intervals generated by bootstrapping

bootstrap_Astro <- comparison.barplot(all_rf_factors_powered_encode, aucvars,
                                      plot_cols =  plot_cols, 
                                      dataset.name = "Astrocytes")
K562_aucvars <- c("rE2G.DNAseOnly","rE2G.Extended", "Distance",
                  "ABC_Score",colnames(K562_EGPs)[str_detect(colnames(K562_EGPs), ".removed|rf")])
K562_aucvars <- K562_aucvars[! K562_aucvars %in% c("EGrf.Extended.ReplaceEnhActivitywithExp","EGrf.Extended.PlusExp")]

#Generate barplot showing AUPRC in K562 models with confidence intervals generated by bootstrapping
bootstrap_K562 <- comparison.barplot(K562_EGPs,K562_aucvars, hit = "Significant_NegEffectSize",
                                     p.value_comp = "EGrf.Extended",
                                     plot_cols = plot_cols, dataset.name = "K562")


cols_benchmarking <- plot_cols[names(plot_cols) %in% c("Distance", "TAPseq.rf", "rE2G.DNAseOnly", 
                                                       "ABC_Score", "rE2G.Extended", "EGrf", "EGrf.Extended", "rE2G.Extended.rf")]

###### Barplot comparing the median AUPRC values (across 1000 fold bootstraps) between the different models in Astrocytes and K562
pdf("8A.Benchmarking.pdf",w_margin / 3, height = w_margin /2)
benchmarkK562Astro(bootstrap_Astro$PR, bootstrap_K562$PR, cols_benchmarking, y.column = "name")
dev.off()

######################## 
###### Fig 7A: Boxplot of AUPRC values across 1000 fold bootstraps between the different models in Astrocytes 
col_boxplot = c(
  EGrf              = "#dd5d2b",
  TAPseq.rf         = "#f3ccde",
  Distance          = "#000000",
  ABC_Score         = "#8dcace",
  rE2G.DNAseOnly    = "#3d8f80",
  rE2G.Extended     = "#3a5f9a",
  EGrf.Extended     = "#6f083d",
  rE2G.Extended.rf  = "grey"
  
)

AUPRC_astro=data.frame(do.call("rbind",bootstrap_Astro$PR_FULL))
AUPRC_astro=melt(AUPRC_astro, variable.name = "Model", value.name = "AUPRC")


#Provide significance data (can be extracted from bootstrap_Astro$PR, where * p <0.05 and ** p< 0.005)
stars_df <- data.frame(
  Model = c("EGrf", "rE2G.DNAseOnly", "ABC_Score", "TAPseq.rf", "Distance"),
  value = c(0.75, 0.75, 0.75, 0.75, 0.75),  # set Y-position above your data range
  label = c("", "*", "**", "**", "**")    # use "" for no star
)

stars_df$Model <- factor(stars_df$Model, levels = c("EGrf", "rE2G.DNAseOnly", "ABC_Score", "TAPseq.rf", "Distance"))


# Generate violin/boxlot for Fig 7A
pdf("7A_BoxplotAstro_AUPRC_1000bootstraps.pdf",w_margin / 2.8, height = w_margin /3.1)

ggplot(data = AUPRC_astro[AUPRC_astro$Model %in% c(
  "Distance", "TAPseq.rf", "rE2G.DNAseOnly", "ABC_Score", "EGrf"
), ],
aes(x = Model, y = AUPRC, fill = Model)) +
  geom_boxplot(outlier.size = 0.1) +
  scale_fill_manual(values = col_boxplot) +
  scale_x_discrete(limits = c("EGrf", "rE2G.DNAseOnly", "ABC_Score", "TAPseq.rf", "Distance"),
                   labels = c("EGrf", "rE2G\nDNAseOnly", "ABC\nScore", "TAPseq.rf", "Distance"))  +
                   
  geom_text(data = stars_df, aes(x = Model, y = value, label = label), inherit.aes = FALSE) +
  theme_bw() + theme(panel.grid = element_blank(),
                     axis.title = ts(8), axis.line = element_line(), legend.position = "",
                     axis.text.x = element_text(size = 6),  
                     axis.text.y = element_text(size = 7))

dev.off()

##Source Data
write.csv(AUPRC_astro[AUPRC_astro$Model %in% c(
  "Distance", "TAPseq.rf", "rE2G.DNAseOnly", "ABC_Score", "EGrf"
), ], "/Volumes/share/mnt/Data0/PROJECTS/CROPSeq/Manuscript/SourceData/SourceData_Fig7A_Boxplot.csv")

######################## 
######ExtFig9C: Boxplots of AUPRC values across 1000 fold bootstraps between the different models in K562
AUPRC_K562=data.frame(do.call("rbind",bootstrap_K562$PR_FULL))
AUPRC_K562=melt(AUPRC_K562, variable.name = "Model", value.name = "AUPRC")

#Provide significance data (can be extracted from bootstrap_Astro$PR, where * p <0.05 and ** p< 0.005)
stars_df_K562 <- data.frame(
  Model =c("EGrf.Extended", "rE2G.Extended", "rE2G.Extended.rf",
           "EGrf", "rE2G.DNAseOnly","ABC_Score","TAPseq.rf","Distance"),
  value = c(0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75),  # set Y-position above your data range
  label = c("", "", "", "**", "**","**", "**", "**")    # use "" for no star
)

AUPRC_K562$Model <- factor(AUPRC_K562$Model, levels = c("EGrf.Extended", "rE2G.Extended", "rE2G.Extended.rf",
                                                              "EGrf", "rE2G.DNAseOnly","ABC_Score","TAPseq.rf","Distance"))
pdf("ExtFig9C_BoxplotK562_AUPRC_1000bootstraps.pdf",w_margin / 1.4, height = w_margin /2.5)
ggplot(data = AUPRC_K562[AUPRC_K562$Model %in% c("EGrf.Extended", "rE2G.Extended", "rE2G.Extended.rf",
                                                 "EGrf", "rE2G.DNAseOnly","ABC_Score","TAPseq.rf","Distance"),],
aes(x = Model, y = AUPRC, fill = Model)) +
  geom_boxplot(outlier.size = 0.1) +
  #geom_violin() +
  scale_fill_manual(values = col_boxplot) +
  scale_x_discrete(limits = c("EGrf.Extended", "rE2G.Extended", "rE2G.Extended.rf",
                                                 "EGrf", "rE2G.DNAseOnly","ABC_Score","TAPseq.rf","Distance"),
                   labels = c("EGrf.\nExtended", "rE2G.\nExtended", "rE2G.\nExtended.rf",
                              "EGrf", "rE2G.\nDNAseOnly","ABC\nScore","TAPseq.rf","Distance"))  +
  
  geom_text(data = stars_df_K562, aes(x = Model, y = value, label = label), inherit.aes = FALSE) +
  theme_bw() + theme(panel.grid = element_blank(),
                     axis.title = ts(9), axis.line = element_line(), legend.position = "",
                     axis.text.x = element_text(size = 7),  
                     axis.text.y = element_text(size = 8))

dev.off()


################
#Code for ExtFig9F
#################

#Making names match
var_colours <- c(#Distance related
  Distance = "tomato1",Gene.Nearest = "tomato3", numTSSEnhGene = "tomato4", #numTSSEnhGene
  #Hic
  HiC.Contact = pals$Primary[1],  #hic_contact
  #promoter activity
  Gene.StabilityIndex = "lightpink3",  Promoter.Activity = pals$Primary[4], #activity_prom
  #Enhancer Chip
  H3K27ac = pals$Primary[6], ATACseq.Pileup = pals$Primary[5],  #Chip.H3K4me3 #DNAse.Pileup #Chip.H3K27ac 
  DNAse = pals$Primary[5], H3K4me3 = "royalblue2", EP300 = "steelblue1") #normalizedEP300_enhActivity
pdf("ExtFig9F.Astrocytes_RFimportance.pdf", width = w_margin /1.5, height = h_margin* 3/11)
#Generate plot showing changes in median AUPRC values after individual variables are removed from a astrocyte model
combined_astro <- combineImportance(bootstrap_Astro$PR, importance_astro,var_colours, line.var = "EGrf", CellType = "Astrocytes")
dev.off()
combined_astro$Basemodel


pdf("8D.K562_RFimportance.pdf", width = w_margin /1.5, height = h_margin*3/11)
#Generate plot showing changes in median AUPRC values after individual variables are removed from a K562 model
combined_K562 <- combineImportance(bootstrap_K562$PR,importance_K562, var_colours, line.var = "EGrf.Extended", CellType = "K562")
dev.off()

####################
#Code for  ExtFig9
####################
#Define variables included in the plot
vars_of_interest <- c("Chip.H3K4me3", "TTseq.TTseq_Total", "TTseq.Ratio_TTversusRNA",
                      "Chip.H3K27ac",
                      "Gene.Nearest", "Distance", "Tobias.Exp_Bound_TF_counts",
                      "Tobias.Exp_Unbound_TF_counts",
                      "ATACseq.Pileup", "numTSSEnhGene", "hic_contact", 
                      "normalizedEP300_enhActivity","activity_prom",
                      "Gene.StabilityIndex", "Beluga.MaxDisScore")

#Match column names: HiC_interaction_NeuN_neg==hic_contact  
colnames(all_rf_factors_powered_encode)[names(all_rf_factors_powered_encode) == "HiC_interaction_NeuN_neg"] <- "hic_contact"

#plot AUPRC values for individual variables considered as predictors
predictionpower_cols <- rep("grey",length(vars_of_interest[! vars_of_interest %in% importance_astro$X]))
names(predictionpower_cols) <-  updateVarNames(vars_of_interest[! vars_of_interest %in% importance_astro$X])
pdf("ExtFig9A.Astrocytes_Variable_Prediction.pdf", width = 3.75/1.5, height = 2.5/1.5)
aucIndividualVariables(all_rf_factors_powered_encode, vars_of_interest, 
                       cols = c(plot_cols,predictionpower_cols),"HitPermissive_NegZ")
dev.off()

predictionpower_cols <- rep("grey",length(vars_of_interest[! vars_of_interest %in% importance_K562$X]))
names(predictionpower_cols) <-  updateVarNames(vars_of_interest[! vars_of_interest %in% importance_K562$X])
pdf("ExtFig9E.K562_Variable_Prediction.pdf", width = 3.75/1.5, height = 2.5/1.5)
aucIndividualVariables(K562_EGPs, vars_of_interest, 
                       cols = c(plot_cols,predictionpower_cols),"Significant_NegEffectSize")
dev.off()
